package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.Springuser;
import com.lhq.springboot.base.enpty.SpringuserExample;
import java.util.List;

public interface SpringuserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table springuser
	 * @mbg.generated  Fri Sep 22 14:59:50 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table springuser
	 * @mbg.generated  Fri Sep 22 14:59:50 CST 2017
	 */
	int insert(Springuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table springuser
	 * @mbg.generated  Fri Sep 22 14:59:50 CST 2017
	 */
	int insertSelective(Springuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table springuser
	 * @mbg.generated  Fri Sep 22 14:59:50 CST 2017
	 */List<Springuser> selectByExample(SpringuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table springuser
	 * @mbg.generated  Fri Sep 22 14:59:50 CST 2017
	 */
	Springuser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table springuser
	 * @mbg.generated  Fri Sep 22 14:59:50 CST 2017
	 */
	int updateByPrimaryKeySelective(Springuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table springuser
	 * @mbg.generated  Fri Sep 22 14:59:50 CST 2017
	 */
	int updateByPrimaryKey(Springuser record);
}