package com.lhq.springboot.util;

import org.mybatis.generator.api.IntrospectedColumn;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.dom.java.Field;
import org.mybatis.generator.api.dom.java.InnerClass;
import org.mybatis.generator.api.dom.java.Method;
import org.mybatis.generator.api.dom.java.Parameter;
import org.mybatis.generator.internal.DefaultCommentGenerator;

public class MyCommentGenerator extends DefaultCommentGenerator {

	public void addFieldComment(Field field,
			IntrospectedTable introspectedTable,
			IntrospectedColumn introspectedColumn) {

		StringBuilder sb = new StringBuilder();

		field.addJavaDocLine("/**"); //$NON-NLS-1$

		StringBuilder sb2 = new StringBuilder();
		sb2.append(" * 字段描述:");
		sb2.append(introspectedColumn.getRemarks());
		field.addJavaDocLine(sb2.toString());
		sb.append(" * 字段:");
		sb.append(introspectedTable.getFullyQualifiedTable());
		sb.append('.');
		sb.append(introspectedColumn.getActualColumnName());
		field.addJavaDocLine(sb.toString());
		addJavadocTag(field, false);
		field.addJavaDocLine(" */"); //$NON-NLS-1$
	}

	public void addGetterComment(Method method,
			IntrospectedTable introspectedTable,
			IntrospectedColumn introspectedColumn) {

		StringBuilder sb = new StringBuilder();

		method.addJavaDocLine("/**"); //$NON-NLS-1$

		sb.append(" * 描述:获取-"); //$NON-NLS-1$
		sb.append(introspectedColumn.getRemarks());
		method.addJavaDocLine(sb.toString());

		method.addJavaDocLine(" *"); //$NON-NLS-1$

		sb.setLength(0);
		sb.append(" * @return the value of "); //$NON-NLS-1$
		sb.append(introspectedTable.getFullyQualifiedTable());
		sb.append('.');
		sb.append(introspectedColumn.getActualColumnName());
		method.addJavaDocLine(sb.toString());

		addJavadocTag(method, false);

		method.addJavaDocLine(" */"); //$NON-NLS-1$
	}

	public void addSetterComment(Method method,
			IntrospectedTable introspectedTable,
			IntrospectedColumn introspectedColumn) {

		StringBuilder sb = new StringBuilder();

		method.addJavaDocLine("/**"); //$NON-NLS-1$
		/**
		 * 
		 * @return
		 */
		sb.append(" * 描述:设置-"); //$NON-NLS-1$
		sb.append(introspectedColumn.getRemarks());
		method.addJavaDocLine(sb.toString());

		method.addJavaDocLine(" *"); //$NON-NLS-1$

		Parameter parm = method.getParameters().get(0);
		sb.setLength(0);
		sb.append(" * @param "); //$NON-NLS-1$
		sb.append(parm.getName());
		sb.append(" the value for "); //$NON-NLS-1$
		sb.append(introspectedTable.getFullyQualifiedTable());
		sb.append('.');
		sb.append(introspectedColumn.getActualColumnName());
		method.addJavaDocLine(sb.toString());
		addJavadocTag(method, false);
		method.addJavaDocLine(" */"); //$NON-NLS-1$
	}
	
	  public void addClassComment(InnerClass innerClass,
	            IntrospectedTable introspectedTable) {
	        
	        StringBuilder sb = new StringBuilder();

	        innerClass.addJavaDocLine("/**"); //$NON-NLS-1$
	        innerClass
	                .addJavaDocLine(" * This class was generated by MyBatis Generator."); //$NON-NLS-1$

	        sb.append(" * This class corresponds to the database table "); //$NON-NLS-1$
	        sb.append(introspectedTable.getFullyQualifiedTable());
	        innerClass.addJavaDocLine(sb.toString());

	        addJavadocTag(innerClass, true);

	        innerClass.addJavaDocLine(" */"); //$NON-NLS-1$
	    }
}
