package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.ColumnsPriv;
import com.lhq.springboot.base.enpty.ColumnsPrivExample;
import com.lhq.springboot.base.enpty.ColumnsPrivKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ColumnsPrivMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table columns_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	long countByExample(ColumnsPrivExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table columns_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByExample(ColumnsPrivExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table columns_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByPrimaryKey(ColumnsPrivKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table columns_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insert(ColumnsPriv record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table columns_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insertSelective(ColumnsPriv record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table columns_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<ColumnsPriv> selectByExample(ColumnsPrivExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table columns_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	ColumnsPriv selectByPrimaryKey(ColumnsPrivKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table columns_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleSelective(@Param("record") ColumnsPriv record,@Param("example") ColumnsPrivExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table columns_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExample(@Param("record") ColumnsPriv record,@Param("example") ColumnsPrivExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table columns_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeySelective(ColumnsPriv record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table columns_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKey(ColumnsPriv record);
}