package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.Db;
import com.lhq.springboot.base.enpty.DbExample;
import com.lhq.springboot.base.enpty.DbKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DbMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table db
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	long countByExample(DbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table db
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByExample(DbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table db
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByPrimaryKey(DbKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table db
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insert(Db record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table db
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insertSelective(Db record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table db
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<Db> selectByExample(DbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table db
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	Db selectByPrimaryKey(DbKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table db
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleSelective(@Param("record") Db record,@Param("example") DbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table db
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExample(@Param("record") Db record,@Param("example") DbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table db
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeySelective(Db record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table db
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKey(Db record);
}