package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.EngineCost;
import com.lhq.springboot.base.enpty.EngineCostExample;
import com.lhq.springboot.base.enpty.EngineCostKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EngineCostMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table engine_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	long countByExample(EngineCostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table engine_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByExample(EngineCostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table engine_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByPrimaryKey(EngineCostKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table engine_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insert(EngineCost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table engine_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insertSelective(EngineCost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table engine_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<EngineCost> selectByExample(EngineCostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table engine_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	EngineCost selectByPrimaryKey(EngineCostKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table engine_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleSelective(@Param("record") EngineCost record,@Param("example") EngineCostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table engine_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExample(@Param("record") EngineCost record,@Param("example") EngineCostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table engine_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeySelective(EngineCost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table engine_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKey(EngineCost record);
}