package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.GtidExecuted;
import com.lhq.springboot.base.enpty.GtidExecutedExample;
import com.lhq.springboot.base.enpty.GtidExecutedKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GtidExecutedMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gtid_executed
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	long countByExample(GtidExecutedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gtid_executed
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByExample(GtidExecutedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gtid_executed
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByPrimaryKey(GtidExecutedKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gtid_executed
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insert(GtidExecuted record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gtid_executed
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insertSelective(GtidExecuted record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gtid_executed
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<GtidExecuted> selectByExample(GtidExecutedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gtid_executed
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	GtidExecuted selectByPrimaryKey(GtidExecutedKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gtid_executed
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleSelective(@Param("record") GtidExecuted record,@Param("example") GtidExecutedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gtid_executed
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExample(@Param("record") GtidExecuted record,@Param("example") GtidExecutedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gtid_executed
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeySelective(GtidExecuted record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gtid_executed
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKey(GtidExecuted record);
}