package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.HelpTopic;
import com.lhq.springboot.base.enpty.HelpTopicExample;
import com.lhq.springboot.base.enpty.HelpTopicWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HelpTopicMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_topic
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	long countByExample(HelpTopicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_topic
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByExample(HelpTopicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_topic
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByPrimaryKey(Integer helpTopicId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_topic
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insert(HelpTopicWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_topic
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insertSelective(HelpTopicWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_topic
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<HelpTopicWithBLOBs> selectByExampleWithBLOBs(HelpTopicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_topic
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<HelpTopic> selectByExample(HelpTopicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_topic
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	HelpTopicWithBLOBs selectByPrimaryKey(Integer helpTopicId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_topic
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleSelective(@Param("record") HelpTopicWithBLOBs record,@Param("example") HelpTopicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_topic
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleWithBLOBs(@Param("record") HelpTopicWithBLOBs record,@Param("example") HelpTopicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_topic
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExample(@Param("record") HelpTopic record,@Param("example") HelpTopicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_topic
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeySelective(HelpTopicWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_topic
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(HelpTopicWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_topic
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKey(HelpTopic record);
}