package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.HelpKeyword;
import com.lhq.springboot.base.enpty.HelpKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HelpKeywordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_keyword
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	long countByExample(HelpKeywordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_keyword
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByExample(HelpKeywordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_keyword
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByPrimaryKey(Integer helpKeywordId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_keyword
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insert(HelpKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_keyword
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insertSelective(HelpKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_keyword
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<HelpKeyword> selectByExample(HelpKeywordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_keyword
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	HelpKeyword selectByPrimaryKey(Integer helpKeywordId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_keyword
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleSelective(@Param("record") HelpKeyword record,@Param("example") HelpKeywordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_keyword
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExample(@Param("record") HelpKeyword record,@Param("example") HelpKeywordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_keyword
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeySelective(HelpKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_keyword
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKey(HelpKeyword record);
}