package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.HelpCategory;
import com.lhq.springboot.base.enpty.HelpCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HelpCategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_category
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	long countByExample(HelpCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_category
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByExample(HelpCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_category
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByPrimaryKey(Short helpCategoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_category
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insert(HelpCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_category
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insertSelective(HelpCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_category
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<HelpCategory> selectByExampleWithBLOBs(HelpCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_category
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<HelpCategory> selectByExample(HelpCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_category
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	HelpCategory selectByPrimaryKey(Short helpCategoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_category
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleSelective(@Param("record") HelpCategory record,@Param("example") HelpCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_category
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleWithBLOBs(@Param("record") HelpCategory record,@Param("example") HelpCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_category
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExample(@Param("record") HelpCategory record,@Param("example") HelpCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_category
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeySelective(HelpCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_category
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(HelpCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help_category
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKey(HelpCategory record);
}