package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.InnodbTableStats;
import com.lhq.springboot.base.enpty.InnodbTableStatsExample;
import com.lhq.springboot.base.enpty.InnodbTableStatsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InnodbTableStatsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table innodb_table_stats
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	long countByExample(InnodbTableStatsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table innodb_table_stats
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByExample(InnodbTableStatsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table innodb_table_stats
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByPrimaryKey(InnodbTableStatsKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table innodb_table_stats
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insert(InnodbTableStats record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table innodb_table_stats
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insertSelective(InnodbTableStats record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table innodb_table_stats
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<InnodbTableStats> selectByExample(InnodbTableStatsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table innodb_table_stats
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	InnodbTableStats selectByPrimaryKey(InnodbTableStatsKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table innodb_table_stats
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleSelective(@Param("record") InnodbTableStats record,@Param("example") InnodbTableStatsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table innodb_table_stats
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExample(@Param("record") InnodbTableStats record,@Param("example") InnodbTableStatsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table innodb_table_stats
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeySelective(InnodbTableStats record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table innodb_table_stats
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKey(InnodbTableStats record);
}