package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.NdbBinlogIndex;
import com.lhq.springboot.base.enpty.NdbBinlogIndexExample;
import com.lhq.springboot.base.enpty.NdbBinlogIndexKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NdbBinlogIndexMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ndb_binlog_index
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	long countByExample(NdbBinlogIndexExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ndb_binlog_index
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByExample(NdbBinlogIndexExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ndb_binlog_index
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByPrimaryKey(NdbBinlogIndexKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ndb_binlog_index
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insert(NdbBinlogIndex record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ndb_binlog_index
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insertSelective(NdbBinlogIndex record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ndb_binlog_index
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<NdbBinlogIndex> selectByExample(NdbBinlogIndexExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ndb_binlog_index
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	NdbBinlogIndex selectByPrimaryKey(NdbBinlogIndexKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ndb_binlog_index
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleSelective(@Param("record") NdbBinlogIndex record,@Param("example") NdbBinlogIndexExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ndb_binlog_index
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExample(@Param("record") NdbBinlogIndex record,@Param("example") NdbBinlogIndexExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ndb_binlog_index
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeySelective(NdbBinlogIndex record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ndb_binlog_index
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKey(NdbBinlogIndex record);
}