package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.Plugin;
import com.lhq.springboot.base.enpty.PluginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PluginMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plugin
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	long countByExample(PluginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plugin
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByExample(PluginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plugin
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByPrimaryKey(String name);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plugin
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insert(Plugin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plugin
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insertSelective(Plugin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plugin
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<Plugin> selectByExample(PluginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plugin
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	Plugin selectByPrimaryKey(String name);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plugin
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleSelective(@Param("record") Plugin record,@Param("example") PluginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plugin
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExample(@Param("record") Plugin record,@Param("example") PluginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plugin
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeySelective(Plugin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plugin
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKey(Plugin record);
}