package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.Proc;
import com.lhq.springboot.base.enpty.ProcExample;
import com.lhq.springboot.base.enpty.ProcKey;
import com.lhq.springboot.base.enpty.ProcWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProcMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proc
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	long countByExample(ProcExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proc
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByExample(ProcExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proc
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByPrimaryKey(ProcKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proc
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insert(ProcWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proc
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insertSelective(ProcWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proc
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<ProcWithBLOBs> selectByExampleWithBLOBs(ProcExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proc
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<Proc> selectByExample(ProcExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proc
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	ProcWithBLOBs selectByPrimaryKey(ProcKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proc
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleSelective(@Param("record") ProcWithBLOBs record,@Param("example") ProcExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proc
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleWithBLOBs(@Param("record") ProcWithBLOBs record,@Param("example") ProcExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proc
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExample(@Param("record") Proc record,@Param("example") ProcExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proc
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeySelective(ProcWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proc
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(ProcWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proc
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKey(Proc record);
}