package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.ServerCost;
import com.lhq.springboot.base.enpty.ServerCostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServerCostMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	long countByExample(ServerCostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByExample(ServerCostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByPrimaryKey(String costName);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insert(ServerCost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insertSelective(ServerCost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<ServerCost> selectByExample(ServerCostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	ServerCost selectByPrimaryKey(String costName);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleSelective(@Param("record") ServerCost record,@Param("example") ServerCostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExample(@Param("record") ServerCost record,@Param("example") ServerCostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeySelective(ServerCost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_cost
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKey(ServerCost record);
}