package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.SlaveRelayLogInfo;
import com.lhq.springboot.base.enpty.SlaveRelayLogInfoExample;
import com.lhq.springboot.base.enpty.SlaveRelayLogInfoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SlaveRelayLogInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_relay_log_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	long countByExample(SlaveRelayLogInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_relay_log_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByExample(SlaveRelayLogInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_relay_log_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByPrimaryKey(String channelName);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_relay_log_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insert(SlaveRelayLogInfoWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_relay_log_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insertSelective(SlaveRelayLogInfoWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_relay_log_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<SlaveRelayLogInfoWithBLOBs> selectByExampleWithBLOBs(SlaveRelayLogInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_relay_log_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<SlaveRelayLogInfo> selectByExample(SlaveRelayLogInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_relay_log_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	SlaveRelayLogInfoWithBLOBs selectByPrimaryKey(String channelName);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_relay_log_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleSelective(@Param("record") SlaveRelayLogInfoWithBLOBs record,@Param("example") SlaveRelayLogInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_relay_log_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleWithBLOBs(@Param("record") SlaveRelayLogInfoWithBLOBs record,@Param("example") SlaveRelayLogInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_relay_log_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExample(@Param("record") SlaveRelayLogInfo record,@Param("example") SlaveRelayLogInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_relay_log_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeySelective(SlaveRelayLogInfoWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_relay_log_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(SlaveRelayLogInfoWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_relay_log_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKey(SlaveRelayLogInfo record);
}