package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.SlaveMasterInfo;
import com.lhq.springboot.base.enpty.SlaveMasterInfoExample;
import com.lhq.springboot.base.enpty.SlaveMasterInfoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SlaveMasterInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_master_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	long countByExample(SlaveMasterInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_master_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByExample(SlaveMasterInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_master_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByPrimaryKey(String channelName);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_master_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insert(SlaveMasterInfoWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_master_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insertSelective(SlaveMasterInfoWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_master_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<SlaveMasterInfoWithBLOBs> selectByExampleWithBLOBs(SlaveMasterInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_master_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<SlaveMasterInfo> selectByExample(SlaveMasterInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_master_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	SlaveMasterInfoWithBLOBs selectByPrimaryKey(String channelName);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_master_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleSelective(@Param("record") SlaveMasterInfoWithBLOBs record,@Param("example") SlaveMasterInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_master_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleWithBLOBs(@Param("record") SlaveMasterInfoWithBLOBs record,@Param("example") SlaveMasterInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_master_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExample(@Param("record") SlaveMasterInfo record,@Param("example") SlaveMasterInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_master_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeySelective(SlaveMasterInfoWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_master_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(SlaveMasterInfoWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_master_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKey(SlaveMasterInfo record);
}