package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.SlaveWorkerInfo;
import com.lhq.springboot.base.enpty.SlaveWorkerInfoExample;
import com.lhq.springboot.base.enpty.SlaveWorkerInfoKey;
import com.lhq.springboot.base.enpty.SlaveWorkerInfoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SlaveWorkerInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_worker_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	long countByExample(SlaveWorkerInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_worker_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByExample(SlaveWorkerInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_worker_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByPrimaryKey(SlaveWorkerInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_worker_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insert(SlaveWorkerInfoWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_worker_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insertSelective(SlaveWorkerInfoWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_worker_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<SlaveWorkerInfoWithBLOBs> selectByExampleWithBLOBs(SlaveWorkerInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_worker_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<SlaveWorkerInfo> selectByExample(SlaveWorkerInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_worker_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	SlaveWorkerInfoWithBLOBs selectByPrimaryKey(SlaveWorkerInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_worker_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleSelective(@Param("record") SlaveWorkerInfoWithBLOBs record,@Param("example") SlaveWorkerInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_worker_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleWithBLOBs(@Param("record") SlaveWorkerInfoWithBLOBs record,@Param("example") SlaveWorkerInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_worker_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExample(@Param("record") SlaveWorkerInfo record,@Param("example") SlaveWorkerInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_worker_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeySelective(SlaveWorkerInfoWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_worker_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(SlaveWorkerInfoWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slave_worker_info
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKey(SlaveWorkerInfo record);
}