package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.SlowLog;
import com.lhq.springboot.base.enpty.SlowLogExample;
import com.lhq.springboot.base.enpty.SlowLogWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SlowLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slow_log
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	long countByExample(SlowLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slow_log
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByExample(SlowLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slow_log
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insert(SlowLogWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slow_log
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insertSelective(SlowLogWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slow_log
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<SlowLogWithBLOBs> selectByExampleWithBLOBs(SlowLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slow_log
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<SlowLog> selectByExample(SlowLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slow_log
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleSelective(@Param("record") SlowLogWithBLOBs record,@Param("example") SlowLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slow_log
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleWithBLOBs(@Param("record") SlowLogWithBLOBs record,@Param("example") SlowLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slow_log
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExample(@Param("record") SlowLog record,@Param("example") SlowLogExample example);
}