package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.TablesPriv;
import com.lhq.springboot.base.enpty.TablesPrivExample;
import com.lhq.springboot.base.enpty.TablesPrivKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TablesPrivMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tables_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	long countByExample(TablesPrivExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tables_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByExample(TablesPrivExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tables_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByPrimaryKey(TablesPrivKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tables_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insert(TablesPriv record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tables_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insertSelective(TablesPriv record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tables_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<TablesPriv> selectByExample(TablesPrivExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tables_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	TablesPriv selectByPrimaryKey(TablesPrivKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tables_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleSelective(@Param("record") TablesPriv record,@Param("example") TablesPrivExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tables_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExample(@Param("record") TablesPriv record,@Param("example") TablesPrivExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tables_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeySelective(TablesPriv record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tables_priv
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKey(TablesPriv record);
}