package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.TbAuthWxUser;
import com.lhq.springboot.base.enpty.TbAuthWxUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbAuthWxUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_wx_user
     *
     * @mbg.generated Mon Oct 16 14:46:45 CST 2017
     */
    long countByExample(TbAuthWxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_wx_user
     *
     * @mbg.generated Mon Oct 16 14:46:45 CST 2017
     */
    int deleteByExample(TbAuthWxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_wx_user
     *
     * @mbg.generated Mon Oct 16 14:46:45 CST 2017
     */
    int deleteByPrimaryKey(String openId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_wx_user
     *
     * @mbg.generated Mon Oct 16 14:46:45 CST 2017
     */
    int insert(TbAuthWxUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_wx_user
     *
     * @mbg.generated Mon Oct 16 14:46:45 CST 2017
     */
    int insertSelective(TbAuthWxUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_wx_user
     *
     * @mbg.generated Mon Oct 16 14:46:45 CST 2017
     */
    List<TbAuthWxUser> selectByExample(TbAuthWxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_wx_user
     *
     * @mbg.generated Mon Oct 16 14:46:45 CST 2017
     */
    TbAuthWxUser selectByPrimaryKey(String openId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_wx_user
     *
     * @mbg.generated Mon Oct 16 14:46:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") TbAuthWxUser record, @Param("example") TbAuthWxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_wx_user
     *
     * @mbg.generated Mon Oct 16 14:46:45 CST 2017
     */
    int updateByExample(@Param("record") TbAuthWxUser record, @Param("example") TbAuthWxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_wx_user
     *
     * @mbg.generated Mon Oct 16 14:46:45 CST 2017
     */
    int updateByPrimaryKeySelective(TbAuthWxUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_auth_wx_user
     *
     * @mbg.generated Mon Oct 16 14:46:45 CST 2017
     */
    int updateByPrimaryKey(TbAuthWxUser record);
}