package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.TimeZoneLeapSecond;
import com.lhq.springboot.base.enpty.TimeZoneLeapSecondExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TimeZoneLeapSecondMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_leap_second
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	long countByExample(TimeZoneLeapSecondExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_leap_second
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByExample(TimeZoneLeapSecondExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_leap_second
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByPrimaryKey(Long transitionTime);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_leap_second
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insert(TimeZoneLeapSecond record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_leap_second
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insertSelective(TimeZoneLeapSecond record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_leap_second
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<TimeZoneLeapSecond> selectByExample(TimeZoneLeapSecondExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_leap_second
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	TimeZoneLeapSecond selectByPrimaryKey(Long transitionTime);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_leap_second
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleSelective(@Param("record") TimeZoneLeapSecond record,@Param("example") TimeZoneLeapSecondExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_leap_second
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExample(@Param("record") TimeZoneLeapSecond record,@Param("example") TimeZoneLeapSecondExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_leap_second
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeySelective(TimeZoneLeapSecond record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_leap_second
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKey(TimeZoneLeapSecond record);
}