package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.TimeZoneTransition;
import com.lhq.springboot.base.enpty.TimeZoneTransitionExample;
import com.lhq.springboot.base.enpty.TimeZoneTransitionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TimeZoneTransitionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_transition
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	long countByExample(TimeZoneTransitionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_transition
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByExample(TimeZoneTransitionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_transition
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByPrimaryKey(TimeZoneTransitionKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_transition
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insert(TimeZoneTransition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_transition
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insertSelective(TimeZoneTransition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_transition
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<TimeZoneTransition> selectByExample(TimeZoneTransitionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_transition
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	TimeZoneTransition selectByPrimaryKey(TimeZoneTransitionKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_transition
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleSelective(@Param("record") TimeZoneTransition record,@Param("example") TimeZoneTransitionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_transition
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExample(@Param("record") TimeZoneTransition record,@Param("example") TimeZoneTransitionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_transition
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeySelective(TimeZoneTransition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_transition
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKey(TimeZoneTransition record);
}