package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.TimeZone;
import com.lhq.springboot.base.enpty.TimeZoneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TimeZoneMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	long countByExample(TimeZoneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByExample(TimeZoneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByPrimaryKey(Integer timeZoneId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insert(TimeZone record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insertSelective(TimeZone record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<TimeZone> selectByExample(TimeZoneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	TimeZone selectByPrimaryKey(Integer timeZoneId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleSelective(@Param("record") TimeZone record,@Param("example") TimeZoneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExample(@Param("record") TimeZone record,@Param("example") TimeZoneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeySelective(TimeZone record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKey(TimeZone record);
}