package com.lhq.springboot.base.mapper;

import com.lhq.springboot.base.enpty.TimeZoneName;
import com.lhq.springboot.base.enpty.TimeZoneNameExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TimeZoneNameMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_name
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	long countByExample(TimeZoneNameExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_name
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByExample(TimeZoneNameExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_name
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int deleteByPrimaryKey(String name);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_name
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insert(TimeZoneName record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_name
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int insertSelective(TimeZoneName record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_name
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */List<TimeZoneName> selectByExample(TimeZoneNameExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_name
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	TimeZoneName selectByPrimaryKey(String name);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_name
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExampleSelective(@Param("record") TimeZoneName record,@Param("example") TimeZoneNameExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_name
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */int updateByExample(@Param("record") TimeZoneName record,@Param("example") TimeZoneNameExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_name
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKeySelective(TimeZoneName record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table time_zone_name
	 * @mbg.generated  Sat Sep 23 23:18:55 CST 2017
	 */
	int updateByPrimaryKey(TimeZoneName record);
}