package com.lhq.springboot.base.enpty;

public class Springuser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column springuser.id
	 * @mbg.generated  Fri Sep 22 14:59:50 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column springuser.name
	 * @mbg.generated  Fri Sep 22 14:59:50 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column springuser.age
	 * @mbg.generated  Fri Sep 22 14:59:50 CST 2017
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column springuser.sex
	 * @mbg.generated  Fri Sep 22 14:59:50 CST 2017
	 */
	private String sex;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column springuser.id
	 * @return  the value of springuser.id
	 * @mbg.generated  Fri Sep 22 14:59:50 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column springuser.id
	 * @param id  the value for springuser.id
	 * @mbg.generated  Fri Sep 22 14:59:50 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column springuser.name
	 * @return  the value of springuser.name
	 * @mbg.generated  Fri Sep 22 14:59:50 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column springuser.name
	 * @param name  the value for springuser.name
	 * @mbg.generated  Fri Sep 22 14:59:50 CST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column springuser.age
	 * @return  the value of springuser.age
	 * @mbg.generated  Fri Sep 22 14:59:50 CST 2017
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column springuser.age
	 * @param age  the value for springuser.age
	 * @mbg.generated  Fri Sep 22 14:59:50 CST 2017
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column springuser.sex
	 * @return  the value of springuser.sex
	 * @mbg.generated  Fri Sep 22 14:59:50 CST 2017
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column springuser.sex
	 * @param sex  the value for springuser.sex
	 * @mbg.generated  Fri Sep 22 14:59:50 CST 2017
	 */
	public void setSex(String sex) {
		this.sex = sex == null ? null : sex.trim();
	}
}